"""Sketch for S65 issue room (December 1982): frontal one-point box, back wall over the full width."""
import json
import sys

S = []


def rect(b, fill, note=None, **kw):
    d = {"type": "rect", "box": [round(v) for v in b], "fill": fill, **kw}
    if note:
        d["note"] = note
    S.append(d)


def poly(pts, fill, note=None):
    d = {"type": "poly", "points": [[round(x), round(y)] for x, y in pts], "fill": fill}
    if note:
        d["note"] = note
    S.append(d)


def ell(b, fill, note=None, **kw):
    d = {"type": "ellipse", "box": [round(v) for v in b], "fill": fill, **kw}
    if note:
        d["note"] = note
    S.append(d)


rect([0, 0, 1920, 200], "#d9d4c6", "ceiling (seen from below, receding to the back wall)")
rect([0, 196, 1920, 8], "#bfb8a6", "ceiling edge / cornice of the back wall")
for x0 in (520, 1220):
    rect([x0, 60, 300, 26], "#f4f2ea", "fluorescent tube fitting on the ceiling")
rect([0, 204, 1920, 536], "#d8cfa8", "back wall: pale ochre-yellow distemper above a darker oil-paint dado")
rect([0, 560, 1920, 180], "#9fa98a", "darker green-grey oil-paint dado (lower wall)")
rect([0, 740, 1920, 340], "#9a8a72", "worn grey-brown linoleum floor")
# door
rect([80, 352, 220, 390], "#7a6a52", "door frame")
rect([90, 362, 200, 378], "#a7865a", "half-glazed wooden entrance door")
rect([110, 382, 160, 170], "#e8eef2", "door glass: snowy courtyard outside")
rect([250, 560, 22, 10], "#5b5b5b", "door handle")
# slogan banner
rect([340, 222, 560, 58], "#b8322a", "red cloth slogan banner with white lettering")
# clock
ell([1000, 236, 72, 72], "#f6f3ea", "round wall clock", outline="#3b3b3b", width=5)
# steel shelving
for x0 in (330, 660, 990):
    rect([x0, 350, 310, 390], "#8c949a", "grey steel shelving unit")
    for k in range(5):
        rect([x0 + 6, 366 + k * 76, 298, 60], "#c4b49a", "shelf with boxes, paint tins, rolls of wire, cans of nails")
# window
rect([1350, 316, 440, 272], "#efece4", "window frame (white painted wood)")
rect([1366, 330, 196, 236], "#cfd8de", "window glass left: courtyard, block end with red parapets, snow")
rect([1578, 330, 196, 236], "#cfd8de", "window glass right")
rect([1340, 574, 460, 14], "#e6e2d8", "window sill")
rect([1390, 610, 360, 90], "#e3ddcf", "cast-iron radiator under the window")
# counter
rect([400, 586, 900, 12], "#b98a55", "counter top (front edge y 597)")
rect([400, 598, 900, 207], "#8e6a45", "wooden issue counter front, panelled (foot y 805)")
for x in (520, 700, 880, 1060, 1180):
    rect([x, 620, 6, 165], "#7a5a3a")
rect([808, 560, 184, 30], "#efe8d6", "open inventory ledger on the counter")
rect([1020, 568, 40, 22], "#5a3a2a", "rubber stamp and ink pad")
rect([1200, 556, 34, 32], "#c8a46a", "glass of tea in a metal holder")
spec = {"note": "S65 natural sketch (December 1982 issue room): frontal camera 2.3 m, horizon y 330, back-wall floor line y 740, "
                "ceiling edge y 200, counter front foot y 805 / top y 597; generated by a sketch script",
        "background": "#d8cfa8", "shapes": S}
json.dump(spec, open(sys.argv[1], "w", encoding="utf-8"), indent=1)
print(len(S), "shapes")
