"""Sketch for S66 garden shed (December 1982): frontal shed at 11 m, Kudlakova 2 block behind, fence, bare trees."""
import json
import sys

S = []


def rect(b, fill, note=None, **kw):
    d = {"type": "rect", "box": [round(v) for v in b], "fill": fill, **kw}
    if note:
        d["note"] = note
    S.append(d)


def poly(pts, fill, note=None):
    d = {"type": "poly", "points": [[round(x), round(y)] for x, y in pts], "fill": fill}
    if note:
        d["note"] = note
    S.append(d)


def line(pts, color, width, note=None):
    d = {"type": "line", "points": [[round(x), round(y)] for x, y in pts], "color": color, "width": width}
    if note:
        d["note"] = note
    S.append(d)


rect([0, 0, 1920, 520], "#cfd6dc", "pale hazy December sky")
# Kudlakova 2 block (40 m): long four-storey panel block with red parapet bands, receding slightly to the left
poly([(470, 70), (1920, 20), (1920, 500), (470, 500)], "#e2ded5", "four-storey panel block Kudlakova 2 (white-grey concrete)")
for k in range(4):
    y0 = 80 + k * 105
    poly([(470, y0 + 40 - k * 0), (1920, y0 - 10), (1920, y0 + 22), (470, y0 + 66)], "#b4554a", "red balcony parapet band")
    poly([(470, y0 - 2), (1920, y0 - 52 + 12), (1920, y0 - 10), (470, y0 + 40)], "#9aa3a8", "loggia recesses / windows")
for x in range(520, 1920, 150):
    line([(x, 60), (x, 500)], "#f1eee6", 5)
rect([470, 60, 26, 440], "#d4cfc4", "block end wall edge")
# bare trees along the fence
for x, h in ((80, 160), (300, 120), (640, 140), (1700, 150), (1850, 110)):
    line([(x, 610), (x, h)], "#5e4c3e", 12, "bare tree")
    line([(x, h + 160), (x - 90, h + 40)], "#5e4c3e", 6)
    line([(x, h + 120), (x + 80, h + 10)], "#5e4c3e", 6)
    line([(x, h + 60), (x - 40, h - 30)], "#5e4c3e", 4)
# fence of the school grounds (16 m)
rect([0, 455, 1920, 150], "#9aa39a", "wire-mesh fence of the school grounds (posts, see-through mesh)")
S.append({"type": "bars", "box": [0, 455, 1920, 150], "step": 96, "bar": 5, "fill": "#5f665f", "vertical": True})
rect([0, 452, 1920, 5], "#5f665f")
# ground behind and around the shed
rect([0, 605, 1920, 120], "#c9ccc4", "snowy grass between the fence and the shed (thin snow, dull grass showing)")
# the shed
rect([880, 322, 740, 20], "#6f6f6c", "flat roof slab edge with a little snow on top")
rect([880, 312, 740, 12], "#eef1f3", "thin snow on the roof")
rect([900, 342, 700, 358], "#c9c0aa", "rendered shed front wall, pale beige-grey, weathered")
rect([1480, 250, 22, 75], "#4c4c4c", "small stovepipe on the roof")
rect([915, 430, 75, 270], "#d9b98a", "stack of new pale wooden laths leaning on the wall")
S.append({"type": "bars", "box": [915, 430, 75, 270], "step": 15, "bar": 3, "fill": "#b8935f", "vertical": True})
rect([1080, 420, 140, 280], "#3a332c", "open doorway, dim interior: sacks, laths, garden tools")
rect([1095, 560, 60, 140], "#a99a7a", "sacks inside")
poly([(1080, 420), (1010, 404), (1010, 716), (1080, 700)], "#8a6a48", "plank door leaf swung open to the left")
rect([1248, 462, 144, 140], "#d7c8a2", "plywood board with the pinned path plan")
rect([1258, 472, 124, 120], "#f2ecd8", "the plan sheet")
line([(1270, 560), (1300, 520), (1340, 530), (1370, 490)], "#3b6fb5", 4)
line([(1270, 500), (1360, 580)], "#c0392b", 3)
rect([1240, 600, 160, 8], "#8a7a5a", "board ledge")
line([(1468, 470), (1452, 650)], "#8a6a48", 7, "shovel handle leaning on the wall")
poly([(1428, 640), (1478, 646), (1472, 705), (1432, 700)], "#7d8186", "shovel blade on the ground")
rect([1600, 342, 40, 358], "#a9a08b", "shed side wall in shade")
# walk area: trodden snowy ground of the yard edge
rect([0, 700, 1920, 380], "#b9b5aa", "trodden ground at the yard edge: packed snow over asphalt and earth (one plain surface)")
rect([0, 700, 1920, 20], "#d9dcd8", "snow edge along the foot of the wall line")
spec = {"note": "S66 natural sketch (December 1982): camera 2.0 m, horizon y 420, shed front foot y 700, roof edge y 336; "
                "generated by a sketch script",
        "background": "#cfd6dc", "shapes": S}
json.dump(spec, open(sys.argv[1], "w", encoding="utf-8"), indent=1)
print(len(S), "shapes")
