"""Builds the game's ambience library, room ambience layers and sound effects from CC0 sources.

  python -X utf8 art/tools/audio_build.py            # everything
  python -X utf8 art/tools/audio_build.py amb sfx    # parts: amb (library + rooms), sfx, credits

Sources (all CC0, see art/source/AUDIO_CREDITS.md, generated by this script):
  fs:<id>          Freesound HQ preview (downloaded by art/tools/freesound.py, licence checked on the page)
  kenney:<path>    Kenney.nl audio packs (CC0), art/candidates/audio/kenney/<pack>/Audio/...
  music:<track>    our own AI-generated score (src/game/assets/music/<track>.ogg), e.g. heard through a radio
  synth            generated here with numpy (tones, pulses, morse, room tone)

Outputs:
  src/game/assets/ambience/beds/<id>.ogg     seamless loops (-24 LUFS)
  src/game/assets/ambience/spots/<id>_<n>.ogg one-shot takes, mono (-22 LUFS each)
  src/game/assets/sfx/<id>_<n>.ogg           action and UI sounds
  src/game/data/audio/ambience.json, sfx.json
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import audio_lib as A  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
CAND = ROOT / "art" / "candidates" / "audio"
ASSETS = ROOT / "src" / "game" / "assets"
DATA = ROOT / "src" / "game" / "data" / "audio"
REGISTRY = ROOT / "art" / "source" / "audio_sources.json"
SR = A.SR
RNG = np.random.default_rng(1960)
BED_LUFS = -24.0
SPOT_LUFS = -22.0
USED: dict[str, set[str]] = {}  # source -> library ids using it (credits)


# ---------------------------------------------------------------- sources and DSP helpers

def src_path(src: str) -> Path:
    kind, _, ref = src.partition(":")
    if kind == "fs":
        for ext in (".ogg", ".mp3"):
            p = CAND / "freesound" / f"{ref}{ext}"
            if p.exists():
                return p
        raise FileNotFoundError(f"freesound {ref} not downloaded (art/tools/freesound.py get {ref})")
    if kind == "kenney":
        return CAND / "kenney" / ref
    if kind == "music":
        return ASSETS / "music" / f"{ref}.ogg"
    raise KeyError(src)


def load(src: str, user: str, start: float = 0.0, dur: float | None = None, mono: bool = False) -> np.ndarray:
    USED.setdefault(src, set()).add(user)
    a = A.decode(src_path(src))
    i0 = int(start * SR)
    i1 = len(a) if dur is None else min(len(a), i0 + int(dur * SR))
    a = a[i0:i1]
    if mono:
        a = a.mean(axis=1, keepdims=True).repeat(2, axis=1)
    return a.astype(np.float32)


def fft_filter(x: np.ndarray, lo: float | None = None, hi: float | None = None, slope_oct: float = 0.5) -> np.ndarray:
    """Zero-phase FFT band filter with smooth (raised-cosine, slope_oct wide) edges. Fast for long files."""
    n = len(x)
    size = 1 << (n - 1).bit_length()
    spec = np.fft.rfft(x, n=size, axis=0)
    f = np.fft.rfftfreq(size, 1 / SR)
    g = np.ones_like(f)
    with np.errstate(divide="ignore"):
        lf = np.log2(np.maximum(f, 1e-3))
    if hi:
        t = np.clip((lf - np.log2(hi)) / slope_oct, 0, 1)
        g *= 0.5 * (1 + np.cos(np.pi * t))
    if lo:
        t = np.clip((np.log2(lo) - lf) / slope_oct, 0, 1)
        g *= 0.5 * (1 + np.cos(np.pi * t))
    out = np.fft.irfft(spec * g[:, None], n=size, axis=0)[:n]
    return out.astype(np.float32)


def fade(x: np.ndarray, fin: float = 0.01, fout: float = 0.05) -> np.ndarray:
    x = x.copy()
    a, b = int(fin * SR), int(fout * SR)
    if a:
        x[:a] *= np.linspace(0, 1, a, dtype=np.float32)[:, None]
    if b:
        x[-b:] *= np.linspace(1, 0, b, dtype=np.float32)[:, None]
    return x


def make_loop(x: np.ndarray, xfade: float = 2.0) -> np.ndarray:
    """Seamless loop: the tail is crossfaded (equal power) into the head, length shrinks by xfade."""
    n = int(xfade * SR)
    if len(x) < 3 * n:
        n = len(x) // 4
    out = x[:len(x) - n].copy()
    t = np.linspace(0, np.pi / 2, n, dtype=np.float32)[:, None]
    out[:n] = x[:n] * np.sin(t) + x[len(x) - n:] * np.cos(t)
    return out


def tick_loop(x: np.ndarray, max_len: float = 26.0, pre: float = 0.3) -> np.ndarray:
    """Seamless loop of a ticking recording: cut just before a tick at both ends (same phase), tiny crossfade."""
    m = np.abs(x.mean(axis=1))
    env = A.moving_mean(m, 220)
    thr = env.max() * 0.3
    idx = np.where((env[1:-1] > thr) & (env[1:-1] >= env[:-2]) & (env[1:-1] > env[2:]))[0] + 1
    ons: list[int] = []
    for i in idx:
        if not ons or i - ons[-1] > 0.2 * SR:
            ons.append(int(i))
    start = ons[1] - int(pre * SR)
    ends = [o for o in ons[2:] if (o - ons[1]) / SR <= max_len]
    # an even number of ticks keeps a tick-tock pair in phase
    count = len(ends) - (len(ends) % 2 == 1)
    end = ends[max(0, count - 1)] - int(pre * SR)
    out = x[start:end].copy()
    n = int(0.02 * SR)
    t = np.linspace(0, np.pi / 2, n, dtype=np.float32)[:, None]
    out[:n] = out[:n] * np.sin(t) + x[end:end + n] * np.cos(t)
    return out


def reverb(x: np.ndarray, size: float = 0.35, mix: float = 0.3) -> np.ndarray:
    """Cheap diffuse tail: decaying noise impulse response by FFT convolution."""
    n = int(size * 3 * SR)
    t = np.arange(n) / SR
    ir = RNG.standard_normal((n, 2)).astype(np.float32) * np.exp(-t / size)[:, None].astype(np.float32)
    ir[: int(0.01 * SR)] = 0
    ir /= np.sqrt((ir ** 2).sum(axis=0, keepdims=True))
    size_fft = 1 << (len(x) + n - 1).bit_length()
    wet = np.fft.irfft(np.fft.rfft(x, size_fft, axis=0) * np.fft.rfft(ir, size_fft, axis=0), size_fft, axis=0)[: len(x)]
    return ((1 - mix) * x + mix * wet).astype(np.float32)


def splits(x: np.ndarray, max_takes: int, min_len: float = 0.12, max_len: float = 5.0, gap: float = 0.25,
           rel_db: float = 28.0) -> list[np.ndarray]:
    """Cut a recording into event takes at silences (RMS below peak - rel_db for > gap seconds)."""
    mono = np.abs(x).mean(axis=1)
    win = int(0.02 * SR)
    env = np.sqrt(A.moving_mean(mono ** 2, win))
    env_db = 20 * np.log10(env + 1e-9)
    thr = max(env_db.max() - rel_db, -60)
    on = env_db > thr
    regions = []
    i, n = 0, len(on)
    g = int(gap * SR)
    while i < n:
        if not on[i]:
            i += 1
            continue
        j = i
        last = i
        while j < n and (on[j] or j - last < g):
            if on[j]:
                last = j
            j += 1
        regions.append((i, last + win))
        i = j
    takes = []
    for s, e in regions:
        if (e - s) / SR < min_len:
            continue
        s = max(0, s - int(0.03 * SR))
        e = min(len(x), e + int(0.15 * SR), s + int(max_len * SR))
        seg = x[s:e]
        takes.append((float(np.sqrt((seg ** 2).mean())), seg))
    takes.sort(key=lambda t: -t[0])
    chosen = [fade(seg, 0.005, min(0.12, len(seg) / SR / 4)) for _, seg in takes[:max_takes]]
    return chosen


def norm(x: np.ndarray, lufs: float) -> np.ndarray:
    out, _, _ = A.normalize(x, lufs, -1.0)
    return out


def to_mono(x: np.ndarray) -> np.ndarray:
    return x.mean(axis=1, keepdims=True).repeat(2, axis=1)


# ---------------------------------------------------------------- synthesis

def t_axis(seconds: float) -> np.ndarray:
    return np.arange(int(seconds * SR)) / SR


def stereo(m: np.ndarray) -> np.ndarray:
    return np.stack([m, m], axis=1).astype(np.float32)


def bell(freq: float, seconds: float, partials=((1, 1.0), (2.76, 0.4), (5.4, 0.2), (8.9, 0.08)), decay: float = 1.2) -> np.ndarray:
    t = t_axis(seconds)
    m = sum(amp * np.sin(2 * np.pi * freq * ratio * t) * np.exp(-t * ratio / decay) for ratio, amp in partials)
    m *= np.minimum(1, t / 0.003)
    tail = max(1, int(len(t) * 0.25))  # smooth end, no click when the buffer stops
    m[-tail:] *= 0.5 * (1 + np.cos(np.linspace(0, np.pi, tail)))
    return m


def pink(seconds: float) -> np.ndarray:
    n = int(seconds * SR)
    white = RNG.standard_normal(n)
    spec = np.fft.rfft(white)
    f = np.fft.rfftfreq(n, 1 / SR)
    spec[1:] /= np.sqrt(f[1:])
    spec[0] = 0
    p = np.fft.irfft(spec, n)
    return p / np.abs(p).max()


def synth_room_tone() -> np.ndarray:
    a = stereo(pink(40.0) * 0.3)
    a[:, 1] = np.roll(a[:, 1], SR * 7)
    return fft_filter(a, 40, 900)


def synth_slow_pulse() -> np.ndarray:
    """S10: insulated bench supply, a soft slow pulse (0.5 Hz) over a 100 Hz hum."""
    t = t_axis(24.0)
    hum = 0.25 * np.sin(2 * np.pi * 100 * t) + 0.08 * np.sin(2 * np.pi * 200 * t) + 0.03 * np.sin(2 * np.pi * 300 * t)
    pulse = 0.5 * (1 - np.cos(2 * np.pi * 0.5 * t)) ** 3 / 8
    tone = np.sin(2 * np.pi * 220 * t) * pulse * 0.5
    return stereo(hum * (0.85 + 0.15 * pulse) + tone)


def synth_instrument_pulse() -> np.ndarray:
    """S30: measuring instrument, a short soft beep every 2 s."""
    t = t_axis(16.0)
    m = np.zeros_like(t)
    for k in range(8):
        s = int(k * 2.0 * SR)
        b = bell(1760, 0.25, partials=((1, 1.0), (2, 0.1)), decay=0.15)
        m[s:s + len(b)] += b * 0.5
    return stereo(m)


def synth_morse() -> np.ndarray:
    """S29: radio-amateur Morse chirping of random letters (no hidden message), 700 Hz, ~18 wpm."""
    unit = 1.2 / 18
    codes = [".-", "-...", "-.-.", "-..", ".", "..-.", "--.", "....", "..", ".---", "-.-", ".-..", "--", "-.", "---",
             ".--.", "--.-", ".-.", "...", "-", "..-", "...-", ".--", "-..-", "-.--", "--.."]
    seconds = 40.0
    t = t_axis(seconds)
    m = np.zeros_like(t)
    pos = 0.5
    while pos < seconds - 3:
        if RNG.random() < 0.12:
            pos += 7 * unit * RNG.integers(2, 6)  # pauses between groups
            continue
        for sym in codes[RNG.integers(0, len(codes))]:
            length = unit * (1 if sym == "." else 3)
            s, e = int(pos * SR), int((pos + length) * SR)
            env = np.ones(e - s)
            r = int(0.004 * SR)
            env[:r] = np.linspace(0, 1, r)
            env[-r:] = np.linspace(1, 0, r)
            m[s:e] += np.sin(2 * np.pi * 700 * t[s:e]) * env * 0.4
            pos += length + unit
        pos += 2 * unit
    noise = fft_filter(stereo(RNG.standard_normal(len(t)) * 0.04), 300, 3000)
    return stereo(m) + noise


def synth_four_tones() -> np.ndarray:
    """S49: four slow, soft tones (a calm mechanical motif), 16 s."""
    seconds = 16.0
    m = np.zeros(int(seconds * SR))
    for k, f in enumerate((392.0, 523.25, 440.0, 587.33)):
        b = bell(f, 4.0, decay=1.8) * 0.5
        s = int((0.3 + k * 3.2) * SR)
        m[s:s + len(b)] += b[: len(m) - s]
    return stereo(m)


def synth_door_chime() -> list[np.ndarray]:
    """S46: a modern two-note electronic door chime."""
    a = bell(988, 1.6, partials=((1, 1.0), (2, 0.15)), decay=0.6)
    b = bell(784, 2.0, partials=((1, 1.0), (2, 0.15)), decay=0.8)
    m = np.zeros(int(2.8 * SR))
    m[: len(a)] += a
    s = int(0.45 * SR)
    m[s:s + len(b)] += b[: len(m) - s]
    return [stereo(m * 0.5)]


def synth_doorbell_two_tone() -> list[np.ndarray]:
    """S05: an old mechanical two-tone gate bell (ding-dong, slightly detuned struck bars)."""
    takes = []
    for detune in (1.0, 0.985):
        hi = bell(659.25 * detune, 2.2, decay=0.9) + 0.3 * bell(661.0 * detune, 2.2, decay=0.9)
        lo = bell(523.25 * detune, 2.6, decay=1.1) + 0.3 * bell(524.8 * detune, 2.6, decay=1.1)
        m = np.zeros(int(3.4 * SR))
        m[: len(hi)] += hi
        s = int(0.55 * SR)
        m[s:s + len(lo)] += lo[: len(m) - s]
        takes.append(stereo(m * 0.4))
    return takes


def synth_metal_tone() -> list[np.ndarray]:
    """S15: the soft metallic tone of a physics model (a struck rod)."""
    return [stereo(bell(f, 3.0, partials=((1, 1.0), (2.756, 0.5), (5.404, 0.25)), decay=1.4) * 0.4) for f in (880, 1046.5)]


def synth_pa_chime() -> list[np.ndarray]:
    """S59: the three-note gong of a school PA before an announcement (distant)."""
    m = np.zeros(int(3.0 * SR))
    for k, f in enumerate((523.25, 659.25, 783.99)):
        b = bell(f, 2.2, decay=0.8) * 0.4
        s = int(k * 0.5 * SR)
        m[s:s + len(b)] += b[: len(m) - s]
    return [stereo(m)]


def synth_ringtone() -> list[np.ndarray]:
    """2020 smartphone ringtone (an original marimba-like motif), two rings."""
    m = np.zeros(int(4.2 * SR))
    motif = (1174.66, 880.0, 987.77, 1318.51, 1174.66, 880.0)
    for rep in range(2):
        for k, f in enumerate(motif):
            b = bell(f, 0.5, partials=((1, 1.0), (4, 0.2), (10, 0.05)), decay=0.25) * 0.4
            s = int((rep * 2.1 + k * 0.17) * SR)
            m[s:s + len(b)] += b[: len(m) - s]
    return [stereo(m)]


def synth_drum_loop() -> np.ndarray:
    """S27: a generic, unauthored 4/4 break heard through a basement door (muffled), 96 BPM, 8 bars."""
    bpm = 96
    beat = 60 / bpm
    seconds = beat * 32
    n = int(seconds * SR)
    m = np.zeros(n)

    def kick():
        t = t_axis(0.35)
        f = 50 + 90 * np.exp(-t / 0.03)
        return np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-t / 0.12)

    def snare():
        t = t_axis(0.25)
        return (RNG.standard_normal(len(t)) * 0.6 + np.sin(2 * np.pi * 190 * t)) * np.exp(-t / 0.06)

    def hat():
        t = t_axis(0.06)
        return RNG.standard_normal(len(t)) * np.exp(-t / 0.015) * 0.25

    k, s, h = kick(), snare(), hat()
    for step in range(32 * 2):  # eighth notes
        pos = int(step * beat / 2 * SR)
        beat_in_bar = (step // 2) % 4
        if step % 2 == 0 and beat_in_bar in (0, 2) or step % 16 == 11:
            m[pos:pos + len(k)] += k[: n - pos]
        if step % 2 == 0 and beat_in_bar in (1, 3):
            m[pos:pos + len(s)] += s[: n - pos] * 0.8
        m[pos:pos + len(h)] += h[: n - pos]
    return fft_filter(stereo(m * 0.5), 40, 700)


def synth_clocks_many() -> np.ndarray:
    """S36: several clocks ticking at different rhythms, layered from the two CC0 clock recordings."""
    a = load("fs:666582", "clocks_many", mono=True)
    b = load("fs:830193", "clocks_many", mono=True)
    n = int(30 * SR)
    out = np.zeros((n, 2), dtype=np.float32)
    for src, rate, gain, pan, off in ((a, 1.0, 1.0, 0.3, 0), (b, 1.0, 0.8, 0.7, 3), (a, 1.33, 0.5, 0.15, 5), (b, 0.78, 0.6, 0.85, 9)):
        idx = (np.arange(n) * rate + off * SR) % (len(src) - 1)
        seg = src[idx.astype(int), 0] * gain
        out[:, 0] += seg * (1 - pan)
        out[:, 1] += seg * pan
    return out


def synth_valve_clicks() -> np.ndarray:
    """S38: a regular valve click every 3 s (from the CC0 valve recording)."""
    click = load("fs:494918", "valve_clicks", mono=True)
    click = splits(click, 1, max_len=0.6)[0]
    n = int(24 * SR)
    out = np.zeros((n, 2), dtype=np.float32)
    for k in range(8):
        s = int((0.4 + 3.0 * k) * SR)
        out[s:s + len(click)] += click[: n - s] * (0.9 + 0.2 * RNG.random())
    return out


def radio(track: str, lo: float = 280, hi: float = 3600, crackle: float = 0.015) -> np.ndarray:
    """Our own score through a small transistor radio: loop body only (already seamless), band-limited, mono."""
    meta = json.loads((DATA / "music.json").read_text(encoding="utf-8"))["tracks"][track]
    a = load(f"music:{track}", "radio_" + track, mono=True)
    a = a[int(meta["loop_start"] * SR):]
    a = fft_filter(a, lo, hi, 0.4)
    a = np.tanh(a * 2.2) / 2.2
    noise = fft_filter(stereo(RNG.standard_normal(len(a)) * crackle), 1000, 6000)
    return (a + noise).astype(np.float32)


# ---------------------------------------------------------------- the ambience library

def lib_beds() -> dict[str, np.ndarray]:
    """id -> stereo bed (before loop + loudness)."""
    def fs(i, user, start=0.0, dur=60.0, **kw):
        return load(f"fs:{i}", user, start, dur, **kw)
    beds = {
        "clock_wall": tick_loop(fs(666582, "clock_wall", 0, 30)),
        "clocks_many": synth_clocks_many(),
        "lawnmower_far": fft_filter(fs(496734, "lawnmower_far", 0, 27), 80, 2500),
        "leaves_wind": fs(523389, "leaves_wind", 10, 70),
        "wind_soft": fft_filter(fs(170471, "wind_soft", 20, 70), 60, 5000),
        "wind_mountain": fs(454092, "wind_mountain", 10, 80),
        "wind_window": fft_filter(fs(557380, "wind_window", 5, 70), 60, 1800),
        "wind_attic": fs(187292, "wind_attic", 5, 80),
        "fridge_hum": fs(753296, "fridge_hum", 0, 26),
        "transformer_hum": fs(453445, "transformer_hum", 0, 28),
        "fluorescent_hum": fs(451918, "fluorescent_hum", 0, 55),
        "ventilation": fs(637804, "ventilation", 0, 60),
        "fan_electric": fs(170870, "fan_electric", 5, 50),
        "server_fans": fs(637377, "server_fans", 0, 29),
        "water_lapping": fs(318064, "water_lapping", 0, 59),
        "water_far": fft_filter(fs(318064, "water_far", 0, 59), 60, 1200),
        "river": fs(487013, "river", 10, 80),
        "fountain": fs(554789, "fountain", 10, 70),
        "birds_suburb": fs(538598, "birds_suburb", 10, 80),
        "countryside": fs(514550, "countryside", 20, 80),
        "sparrows": fs(320287, "sparrows", 10, 80),
        "chickens": fs(51766, "chickens", 0, 42),
        "playground": fs(238549, "playground", 20, 80),
        "playground_far": fft_filter(fs(238549, "playground_far", 100, 70), 100, 2500),
        "school_far": fft_filter(fs(324992, "school_far", 10, 80), 100, 1500),
        "walla_room": fft_filter(fs(475650, "walla_room", 20, 80), 100, 3000),
        "walla_muffled": fft_filter(fs(475650, "walla_muffled", 120, 80), 100, 1200),
        "walla_small": fs(653920, "walla_small", 0, 28),
        "market": fs(784650, "market", 0, 75),
        "city_morning": fs(251428, "city_morning", 10, 80),
        "city_far": fft_filter(fs(251428, "city_far", 90, 80), 60, 1500),
        "street_muffled": fft_filter(fs(119934, "street_muffled", 0, 57), 60, 900),
        "town_square": fs(119934, "town_square", 0, 57),
        "lobby": fs(152434, "lobby", 0, 60),
        "cafe": fs(746428, "cafe", 10, 80),
        "tourists": fs(378263, "tourists", 0, 33),
        "cable_car_hum": fs(263134, "cable_car_hum", 0, 65),
        "cable_car_far": fft_filter(fs(263134, "cable_car_far", 0, 65), 60, 900),
        "cabin_interior": fs(377749, "cabin_interior", 10, 80),
        "funicular": fs(442493, "funicular", 0, 60),
        "tape_hiss": fs(430975, "tape_hiss", 0, 49),
        "underpass": fs(196114, "underpass", 0, 78),
        "kettle_glass": fft_filter(fs(475871, "kettle_glass", 10, 60), 80, 1500),
        "teletype": fs(483336, "teletype", 0, 78),
        "tram_city": fs(582919, "tram_city", 20, 80),
        "projector": fs(454120, "projector", 0, 38),
        "drip_room": fft_filter(fs(609771, "drip_room", 0, 38), 100, 3000),
        "room_tone": synth_room_tone(),
        "slow_pulse": synth_slow_pulse(),
        "instrument_pulse": synth_instrument_pulse(),
        "morse": synth_morse(),
        "four_tones": synth_four_tones(),
        "drum_loop_muffled": synth_drum_loop(),
        "valve_clicks": synth_valve_clicks(),
        "radio_1982": radio("1982"),
        "radio_1995": radio("1995"),
        "radio_2020": radio("2020"),
        "accordion_busker": reverb(fft_filter(load("music:1960", "accordion_busker", 22.05, mono=True), 180, 7000), 0.6, 0.25),
        "video_quiet": fft_filter(load("music:2035", "video_quiet", 29.33, mono=True), 150, 2500),
        "phone_call_laptop": np.tanh(fft_filter(fs(260124, "phone_call_laptop", 0, 19.7, mono=True), 320, 3400, 0.3) * 3) / 3,
    }
    return beds


# loops whose source is already seamless (no crossfade needed)
SEAMLESS = {"clock_wall", "radio_1982", "radio_1995", "radio_2020", "accordion_busker", "video_quiet", "slow_pulse", "instrument_pulse",
            "four_tones", "drum_loop_muffled", "valve_clicks", "clocks_many"}


def lib_spots() -> dict[str, list[np.ndarray]]:
    """id -> list of takes."""
    def fs(i, user, start=0.0, dur=None, **kw):
        return load(f"fs:{i}", user, start, dur, **kw)

    def sp(i, user, n=4, max_len=5.0, **kw):
        return splits(fs(i, user), n, max_len=max_len, **kw)

    spots = {
        "dog_bark": sp(581478, "dog_bark", 3, 2.5) + sp(846342, "dog_bark", 3, 3.0),
        "van_reverse": [fade(fft_filter(fs(197166, "van_reverse", 0, 6.0), 200, 4000), 0.2, 0.8)],
        "bag_rustle": sp(365520, "bag_rustle", 4, 2.5),
        "pen_writing": [fade(fs(751055, "pen_writing", 0.2, 3.5), 0.1, 0.4)],
        "shop_bell": sp(494565, "shop_bell", 2, 4.0),
        "doorbell_two_tone": synth_doorbell_two_tone(),
        "phone_speaker": [fade(np.tanh(fft_filter(fs(260124, "phone_speaker", s, 4.0, mono=True), 400, 3200, 0.3) * 4) / 4, 0.1, 0.4)
                          for s in (0.0, 6.0, 12.0)],
        "phone_vibrate": [fade(fs(384487, "phone_vibrate", 0, 3.0), 0.01, 0.1)],
        "bus_pass": [fade(fft_filter(fs(153538, "bus_pass", 0, 16.0), 40, 6000), 1.5, 2.5)],
        "bicycle_bell": sp(383631, "bicycle_bell", 2, 3.0),
        "bike_pass": [fade(fs(276001, "bike_pass", 0, 10.0), 1.0, 2.0)],
        "floor_creak": sp(646695, "floor_creak", 1, 1.5) + sp(495659, "floor_creak", 4, 2.5),
        "metal_shimmer": [fade(fs(342603, "metal_shimmer", 0, 8.0), 0.3, 2.5)],
        "ball_bounce": sp(74926, "ball_bounce", 4, 1.2),
        "footsteps_reverb": [fade(fs(793361, "footsteps_reverb", 0, 9.0), 0.3, 1.5), fade(fs(793361, "footsteps_reverb", 9.0, 9.0), 0.3, 1.5)],
        "keys": sp(166007, "keys", 2, 3.5),
        "chalk": sp(210319, "chalk", 3, 3.0),
        "kids_whisper": [fade(fft_filter(fs(478356, "kids_whisper", s, 6.0), 150, 1800), 0.5, 1.0) for s in (0.0, 7.0, 13.0)],
        "cupboard_creak": sp(855584, "cupboard_creak", 2, 4.0),
        "metal_tone": synth_metal_tone(),
        "whistle_far": [fft_filter(t, 300, 5000) for t in sp(218318, "whistle_far", 2, 2.0)],
        "kids_laugh": [fade(fs(416703, "kids_laugh", 0, 6.7), 0.1, 0.8)],
        "newspaper": sp(232982, "newspaper", 3, 2.0),
        "blind_rattle": sp(785117, "blind_rattle", 3, 2.5),
        "spring": sp(472477, "spring", 2, 1.5),
        "coins": sp(443858, "coins", 3, 2.5),
        "drawer": sp(189300, "drawer", 4, 2.5),
        "metal_drawer": sp(553231, "metal_drawer", 3, 3.0),
        "stamp": sp(470710, "stamp", 2, 1.0),
        "scissors": sp(377630, "scissors", 4, 3.0),
        "sewing_machine": [fade(fs(187730, "sewing_machine", st, 6.0), 0.15, 0.6) for st in (2.0, 12.0, 24.0)],
        "cassette_click": sp(218938, "cassette_click", 4, 1.0),
        "skateboard": [fade(fs(243765, "skateboard", 0, 10.0), 0.5, 2.0)],
        "ship_horn": [fade(fft_filter(fs(636075, "ship_horn", 0, 6.0), 40, 2000), 0.3, 1.5)],
        "steam_train": [fade(fs(9923, "steam_train", 0, 27.0), 2.0, 4.0), fade(fs(473905, "steam_train", 0, 13.0), 1.0, 3.0)],
        "tram_bell": sp(497561, "tram_bell", 2, 2.4),
        "tram_pass": [fade(fs(110381, "tram_pass", 20, 18.0), 2.0, 3.0), fade(fs(698204, "tram_pass", 0, 20.0), 2.0, 3.0)],
        "tram_brakes": [fade(fs(385284, "tram_brakes", s, 10.0), 1.0, 2.0) for s in (20.0, 60.0)],
        "piano_tuning": [fade(t, 0.005, 0.5) for t in sp(740481, "piano_tuning", 1, 3.7)],
        "footsteps_wood": [fade(fs(546362, "footsteps_wood", s, 4.5), 0.2, 0.8) for s in (0.0, 5.0)],
        "handcart": [fade(fs(496727, "handcart", s, 8.0), 0.5, 1.5) for s in (0.0, 10.0)],
        "door_creak": sp(393801, "door_creak", 1, 6.0) + sp(590950, "door_creak", 1, 2.0),
        "file_rasp": sp(532136, "file_rasp", 4, 2.0),
        "pencil": [fade(fs(387927, "pencil", s, 4.0), 0.3, 0.8) for s in (0.0, 6.0, 12.0)],
        "metal_chord": [fade(fs(398496, "metal_chord", 0, 4.0), 0.005, 1.0)],
        "suitcase": [fade(fs(423707, "suitcase", 0, 11.0), 0.5, 1.5)],
        "cups": sp(429494, "cups", 3, 1.5) + sp(352872, "cups", 2, 3.0),
        "page_turn": sp(336374, "page_turn", 4, 1.5),
        "ticket_print": [fade(fs(345057, "ticket_print", 0, 7.4), 0.05, 0.5)],
        "door_chime": synth_door_chime(),
        "banner_flap": [fade(fs(701647, "banner_flap", s, 4.0), 0.3, 1.0) for s in (0.0, 5.0)],
        "mop": [fade(fs(497178, "mop", 0, 6.5), 0.2, 0.8)],
        "cart_squeak": [fade(fs(482744, "cart_squeak", 0, 7.4), 0.5, 1.0)],
        "glass_jars": sp(331974, "glass_jars", 4, 1.5),
        "sack": [fade(fs(554561, "sack", s, 3.0), 0.2, 0.6) for s in (2.0, 10.0, 20.0)],
        "wood_knock": sp(553297, "wood_knock", 1, 1.6) + [fade(fs(213066, "wood_knock", 2.0, 3.0), 0.05, 0.5)],
        "wood_jostle": [fade(fs(213066, "wood_jostle", s, 4.0), 0.1, 0.8) for s in (0.0, 8.0, 15.0)],
        "hiking_steps": [fade(fs(828885, "hiking_steps", 0, 8.0), 0.5, 1.5), fade(fs(332719, "hiking_steps", 0, 8.0), 0.5, 1.5)],
        "phone_ring": synth_ringtone(),
        "pa_chime": [fft_filter(reverb(t, 0.8, 0.4), 300, 4000) for t in synth_pa_chime()],
    }
    return spots


# room -> layers: (sound, dB) for beds; (sound, dB, [every_min, every_max], optional dict) for spots
ROOMS: dict[str, list] = {
    "S01": [("clock_wall", 0), ("lawnmower_far", -9), ("radio_2020", -14)],
    "S02": [("leaves_wind", 0), ("birds_suburb", -8), ("dog_bark", -8, [10, 26], {"x": [100, 700]}), ("van_reverse", -16, [30, 60])],
    "S03": [("walla_room", -4), ("wind_soft", -16), ("bag_rustle", -6, [6, 14]), ("pen_writing", -10, [10, 22])],
    "S04": [("fridge_hum", -5), ("birds_suburb", -14), ("shop_bell", -9, [18, 40])],
    "S05": [("leaves_wind", 0), ("birds_suburb", -12), ("doorbell_two_tone", -16, [45, 90])],
    "S06": [("leaves_wind", -3), ("kettle_glass", -18), ("phone_speaker", -12, [8, 18])],
    "S07": [("wind_soft", 0), ("bus_pass", -10, [22, 45]), ("phone_vibrate", -14, [25, 55])],
    "S08": [("water_lapping", -2), ("birds_suburb", -6), ("bike_pass", -10, [22, 45]), ("bicycle_bell", -14, [35, 75])],
    "S09": [("room_tone", -8), ("floor_creak", -6, [6, 15]), ("metal_shimmer", -12, [15, 30])],
    "S10": [("transformer_hum", -6), ("slow_pulse", -8)],
    "S11": [("city_morning", 0), ("tram_bell", -8, [15, 35]), ("tram_pass", -6, [35, 70])],
    "S12": [("sparrows", -4), ("playground_far", -6), ("ball_bounce", -12, [8, 20])],
    "S13": [("room_tone", -8), ("school_far", -10), ("footsteps_reverb", -8, [10, 25]), ("keys", -10, [15, 35])],
    "S14": [("clock_wall", -8), ("room_tone", -12), ("kids_whisper", -12, [15, 30]), ("chalk", -10, [10, 25])],
    "S15": [("room_tone", -8), ("cupboard_creak", -10, [15, 35]), ("metal_tone", -12, [12, 30])],
    "S16": [("tape_hiss", -6), ("school_far", -14), ("room_tone", -12)],
    "S17": [("playground", 0), ("kids_laugh", -8, [10, 25]), ("ball_bounce", -8, [6, 15]), ("whistle_far", -14, [25, 60])],
    "S18": [("city_morning", -8), ("radio_1995", -10), ("newspaper", -10, [10, 25]), ("blind_rattle", -12, [20, 45])],
    "S19": [("city_far", -8), ("accordion_busker", -10), ("tram_pass", -6, [40, 80]), ("tram_bell", -12, [25, 60])],
    "S20": [("radio_1995", -8), ("fan_electric", -8), ("spring", -10, [10, 25])],
    "S21": [("town_square", 0), ("bus_pass", -10, [20, 40]), ("coins", -12, [10, 30])],
    "S22": [("street_muffled", -10), ("room_tone", -10), ("page_turn", -10, [10, 25]), ("shop_bell", -12, [30, 60])],
    "S23": [("clock_wall", -8), ("room_tone", -12), ("drawer", -10, [12, 30]), ("stamp", -10, [10, 25])],
    "S24": [("drip_room", -8), ("room_tone", -12), ("scissors", -10, [10, 25])],
    "S25": [("market", 0), ("coins", -10, [10, 25]), ("tram_pass", -14, [40, 80])],
    "S26": [("room_tone", -10), ("sewing_machine", -8, [6, 16]), ("scissors", -10, [12, 25])],
    "S27": [("drum_loop_muffled", -6), ("tape_hiss", -16), ("cassette_click", -10, [20, 40])],
    "S28": [("underpass", 0), ("footsteps_reverb", -8, [8, 18]), ("skateboard", -8, [20, 45])],
    "S29": [("fan_electric", -6), ("morse", -10)],
    "S30": [("river", 0), ("instrument_pulse", -14), ("ship_horn", -14, [60, 120])],
    "S31": [("countryside", -4), ("clock_wall", -12), ("steam_train", -8, [40, 80])],
    "S32": [("countryside", -2), ("chickens", -8), ("bicycle_bell", -10, [20, 45])],
    "S33": [("room_tone", -10), ("teletype", -12), ("stamp", -6, [8, 18]), ("pen_writing", -10, [10, 20])],
    "S34": [("room_tone", -12), ("piano_tuning", -8, [4, 9]), ("footsteps_wood", -10, [12, 25])],
    "S35": [("chickens", -6), ("countryside", -10), ("handcart", -10, [25, 50]), ("door_creak", -10, [20, 45])],
    "S36": [("clocks_many", 0), ("room_tone", -12), ("file_rasp", -12, [12, 25])],
    "S37": [("countryside", -2), ("leaves_wind", -4), ("pencil", -10, [10, 25])],
    "S38": [("wind_soft", -10), ("drip_room", -8), ("valve_clicks", -10)],
    "S39": [("fan_electric", -8), ("metal_chord", -10, [12, 25]), ("pencil", -12, [15, 30])],
    "S40": [("wind_attic", -4), ("floor_creak", -10, [10, 25])],
    "S41": [("cable_car_hum", -4), ("tourists", -8), ("leaves_wind", -10)],
    "S42": [("fountain", -8), ("tourists", -14), ("suitcase", -8, [12, 25]), ("door_creak", -14, [20, 40])],
    "S43": [("lobby", -4), ("ventilation", -12), ("cups", -10, [8, 18])],
    "S44": [("ventilation", -12), ("video_quiet", -16), ("page_turn", -10, [10, 25])],
    "S45": [("water_lapping", -4), ("leaves_wind", -4), ("hiking_steps", -10, [15, 35])],
    "S46": [("walla_small", -8), ("ticket_print", -8, [15, 30]), ("door_chime", -12, [25, 50])],
    "S47": [("wind_window", -6), ("cable_car_far", -14), ("projector", -10)],
    "S48": [("server_fans", -6), ("wind_window", -14)],
    "S49": [("four_tones", -10), ("wind_window", -12)],
    "S50": [("wind_mountain", -2), ("tourists", -12)],
    "S51": [("tram_city", -4), ("walla_muffled", -12)],
    "S52": [("wind_soft", -4), ("city_far", -10)],
    "S53": [("fluorescent_hum", -6), ("room_tone", -12), ("phone_ring", -14, [30, 60])],
    "S54": [("ventilation", -6), ("phone_call_laptop", -14)],
    "S55": [("wind_soft", 0), ("leaves_wind", -4, None, {"after": "E10"}), ("birds_suburb", -6, None, {"after": "E10"})],
    "S56": [("room_tone", -10), ("phone_vibrate", -12, [25, 50]), ("wood_knock", -10, [10, 20])],
    "S57": [("city_far", -10), ("wind_soft", -12), ("radio_1982", -10), ("tram_brakes", -8, [30, 60])],
    "S58": [("sparrows", -4), ("school_far", -10), ("banner_flap", -10, [10, 20])],
    "S59": [("school_far", -14), ("room_tone", -10), ("footsteps_reverb", -10, [10, 25]), ("mop", -10, [15, 30]),
            ("pa_chime", -16, [45, 90])],
    "S60": [("room_tone", -12), ("radio_1982", -12), ("chalk", -10, [10, 25]), ("newspaper", -14, [12, 25])],
    "S61": [("wind_soft", -2), ("cart_squeak", -10, [25, 50]), ("ball_bounce", -14, [12, 25])],
    "S62": [("radio_1982", -14), ("room_tone", -10), ("glass_jars", -12, [12, 25]), ("door_creak", -12, [25, 50])],
    "S63": [("clock_wall", -6), ("room_tone", -10)],
    "S64": [("radio_1982", -12), ("file_rasp", -10, [10, 20]), ("wood_knock", -10, [10, 25])],
    "S65": [("room_tone", -10), ("stamp", -8, [10, 20]), ("metal_drawer", -10, [12, 25]), ("newspaper", -12, [15, 30])],
    "S66": [("water_far", -14), ("room_tone", -10), ("sack", -10, [12, 25]), ("wood_jostle", -12, [15, 30])],
    "S67": [("funicular", -4), ("wind_mountain", -8), ("hiking_steps", -10, [12, 25])],
    "S68": [("cabin_interior", -4), ("wind_window", -12), ("walla_small", -14)],
}


def build_ambience() -> None:
    beds_dir = ASSETS / "ambience" / "beds"
    spots_dir = ASSETS / "ambience" / "spots"
    library: dict[str, dict] = {}
    used_beds = {layer[0] for layers in ROOMS.values() for layer in layers if len(layer) == 2 or layer[2] is None}
    used_spots = {layer[0] for layers in ROOMS.values() for layer in layers if len(layer) > 2 and layer[2] is not None}
    beds = lib_beds()
    for bid, audio in beds.items():
        if bid not in used_beds:
            continue
        loop = audio if bid in SEAMLESS else make_loop(audio, 2.5)
        loop = norm(loop, BED_LUFS)
        dest = beds_dir / f"{bid}.ogg"
        A.encode_ogg(dest, loop, quality=3.0)
        library[bid] = {"kind": "loop", "files": [f"ambience/beds/{bid}.ogg"], "seconds": round(len(loop) / SR, 2)}
        print(f"bed  {bid:20s} {len(loop) / SR:6.1f}s")
    spots = lib_spots()
    for sid, takes in spots.items():
        if sid not in used_spots:
            continue
        files = []
        for k, take in enumerate(takes):
            take = norm(to_mono(take), SPOT_LUFS)
            dest = spots_dir / f"{sid}_{k + 1}.ogg"
            A.encode_ogg(dest, take[:, :1].copy(), quality=4.0)
            files.append(f"ambience/spots/{sid}_{k + 1}.ogg")
        library[sid] = {"kind": "spot", "files": files}
        print(f"spot {sid:20s} {len(files)} takes")
    missing = (used_beds | used_spots) - set(library)
    if missing:
        raise SystemExit(f"layers use unknown sounds: {sorted(missing)}")
    rooms = {}
    for room, layers in ROOMS.items():
        out = []
        for layer in layers:
            entry = {"sound": layer[0], "db": layer[1]}
            if len(layer) > 2 and layer[2] is not None:
                entry["every"] = layer[2]
            if len(layer) > 3:
                entry.update(layer[3])
            out.append(entry)
        rooms[room] = {"layers": out}
    DATA.mkdir(parents=True, exist_ok=True)
    (DATA / "ambience.json").write_text(json.dumps({
        "note": "Room ambience (rooms[].ambience of game.json realised as layers). kind loop = seamless bed, "
                "spot = one-shot takes fired every [min,max] s from a random x (canvas px). db is relative to the "
                "normalised file (beds -24 LUFS, spots -22 LUFS). after/until: action ids. Built by art/tools/audio_build.py.",
        "library": library, "rooms": rooms}, ensure_ascii=False, indent=1), encoding="utf-8")


# ---------------------------------------------------------------- sound effects

K_UI = "kenney:kenney_interface-sounds/Audio/"
K_UI2 = "kenney:kenney_ui-audio/Audio/"
K_RPG = "kenney:kenney_rpg-audio/Audio/"
K_PIZ = "kenney:kenney_music-jingles/Audio/Pizzicato jingles/"

# id -> (sources, db, pitch jitter, cooldown, lufs target)
SFX = {
    # actions[].sfx
    "item_soft": ([K_RPG + "cloth1.ogg", K_RPG + "cloth2.ogg", K_RPG + "handleSmallLeather.ogg", K_RPG + "handleSmallLeather2.ogg"], 0, 0.05, 0.1, -20),
    "paper": ([K_RPG + "bookFlip2.ogg", K_RPG + "bookFlip3.ogg", "fs:232982#0"], 0, 0.04, 0.1, -20),
    "tool_click": ([K_RPG + "metalClick.ogg", K_RPG + "metalLatch.ogg"], 0, 0.04, 0.1, -20),
    "soft_success": ([K_PIZ + "jingles_PIZZI10.ogg"], 0, 0.0, 0.3, -19),
    # UI and game events
    "ui_click": ([K_UI + "click_001.ogg"], 0, 0.03, 0.04, -24),
    "ui_hover": ([K_UI + "tick_002.ogg"], 0, 0.05, 0.06, -32),
    "ui_toggle": ([K_UI + "toggle_002.ogg"], 0, 0.02, 0.05, -24),
    "ui_slider": ([K_UI + "tick_004.ogg"], 0, 0.02, 0.05, -28),
    "item_select": ([K_UI + "select_001.ogg"], 0, 0.02, 0.05, -24),
    "item_deselect": ([K_UI + "back_002.ogg"], 0, 0.02, 0.05, -26),
    "item_added": ([K_UI + "pluck_001.ogg"], 0, 0.0, 0.2, -24),
    "new_goal": ([K_PIZ + "jingles_PIZZI13.ogg"], 0, 0.0, 0.5, -23),
    "inventory_open": ([K_RPG + "clothBelt.ogg"], 0, 0.03, 0.1, -22),
    "inventory_close": ([K_RPG + "beltHandle1.ogg"], 0, 0.03, 0.1, -24),
    "journal_open": ([K_RPG + "bookOpen.ogg"], 0, 0.02, 0.1, -22),
    "journal_close": ([K_RPG + "bookClose.ogg"], 0, 0.02, 0.1, -24),
    "map_open": ([K_RPG + "bookFlip1.ogg"], 0, 0.02, 0.1, -22),
    "map_close": ([K_RPG + "bookFlip3.ogg"], 0, 0.02, 0.1, -24),
    "pause_open": ([K_UI + "open_002.ogg"], 0, 0.0, 0.1, -24),
    "pause_close": ([K_UI + "close_002.ogg"], 0, 0.0, 0.1, -24),
    "puzzle_open": ([K_RPG + "metalLatch.ogg"], 0, 0.02, 0.2, -22),
    "puzzle_success": ([K_PIZ + "jingles_PIZZI02.ogg"], 0, 0.0, 0.5, -18),
    "puzzle_fail": ([K_PIZ + "jingles_PIZZI09.ogg"], 0, 0.0, 0.5, -22),
    "era_transition": (["fs:326091"], 0, 0.0, 1.0, -19),
    "cutscene_start": ([K_PIZ + "jingles_PIZZI15.ogg"], 0, 0.0, 1.0, -21),
    "saved": ([K_UI + "glass_002.ogg"], 0, 0.0, 0.5, -26),
}

EVENTS = {name: name for name in SFX if not name.startswith(("item_soft", "paper", "tool_click", "soft_success"))}


def build_sfx() -> None:
    sfx_dir = ASSETS / "sfx"
    sounds = {}
    for sid, (sources, db, pitch, cooldown, lufs) in SFX.items():
        files = []
        for k, src in enumerate(sources):
            ref, _, take = src.partition("#")
            audio = load(ref, "sfx:" + sid)
            if take:
                audio = splits(audio, 4, max_len=2.0)[int(take)]
            if ref.startswith("fs:326091"):
                audio = fade(audio[: int(3.6 * SR)], 0.01, 0.8)
            # trim leading silence, short fades
            mono = np.abs(audio).max(axis=1)
            lead = int(np.argmax(mono > 10 ** (-50 / 20)))
            audio = fade(audio[lead:], 0.002, min(0.03, len(audio) / SR / 5))
            if len(audio) < int(0.4 * SR):  # ebur128 needs 400 ms: measure with padding
                padded = np.concatenate([audio, np.zeros((int(0.4 * SR), 2), np.float32)])
                lufs_now, _ = A.loudness(padded)
                audio = audio * 10 ** ((lufs - lufs_now) / 20)
                if np.abs(audio).max() > 0.89:
                    audio = audio * (0.89 / np.abs(audio).max())
            else:
                audio = norm(audio, lufs)
            dest = sfx_dir / f"{sid}_{k + 1}.ogg"
            A.encode_ogg(dest, audio, quality=5.0)
            files.append(f"sfx/{sid}_{k + 1}.ogg")
        sounds[sid] = {"files": files, "db": db, "pitch": pitch, "cooldown": cooldown}
        print(f"sfx {sid:16s} {len(files)} file(s)")
    DATA.mkdir(parents=True, exist_ok=True)
    (DATA / "sfx.json").write_text(json.dumps({
        "note": "Sound effects: ids used by game.json actions[].sfx (item_soft, paper, tool_click, soft_success) and "
                "UI/game events (events: event name -> sound id, raised by scripts/Audio/AudioService.cs). Files are "
                "loudness-matched; db/pitch/cooldown are applied at play time. Built by art/tools/audio_build.py.",
        "sounds": sounds, "events": EVENTS}, ensure_ascii=False, indent=1), encoding="utf-8")


# ---------------------------------------------------------------- credits

def build_credits() -> None:
    reg = json.loads(REGISTRY.read_text(encoding="utf-8")) if REGISTRY.exists() else {}
    fsreg = reg.get("freesound", {})
    music = json.loads((DATA / "music.json").read_text(encoding="utf-8"))["tracks"]
    lines = [
        "# Audio credits and licences",
        "",
        "Generated by `art/tools/audio_build.py` (re-run after changing sources). Product decision 2026-10-05:",
        "AI-generated original music per era + free CC0 sound effects and ambience.",
        "",
        "## Music (original, AI-generated for this game)",
        "",
        "Generated with Google **Lyria 3 Pro** via fal.ai (`fal-ai/lyria3/pro`, USD 0.08 per track, logged in",
        "`art/spend-log.csv`), prompts in `art/tools/music.py`, raw files and the full request/response in",
        "`art/masters/music/`. Mastered (loop points, one-beat baked crossfade, -16 LUFS, OGG Vorbis) by",
        "`art/tools/audio_master.py`. Lyria output carries Google's inaudible SynthID watermark. The fal.ai /",
        "Google terms grant the user the rights to generated output; no third-party melody was requested",
        "(prompts describe moods and instruments only, never an existing piece or artist).",
        "",
        "| file | raw generation | length | loop |",
        "|---|---|---:|---|",
    ]
    for t in music.values():
        lines.append(f"| `src/game/assets/{t['file']}` | `{t['source']}` | {t['length']:.0f} s | {t['loop_start']:.2f} s → end |")
    lines += [
        "",
        "Our own score is also reused inside the world: `radio_1982/1995/2020` (the era theme through a small",
        "transistor radio), `accordion_busker` (S19, the 1960 theme as a street accordion) and `video_quiet` (S44).",
        "",
        "## Sound effects and ambience (CC0 1.0 only)",
        "",
        "All third-party sounds are **CC0 1.0 Universal** (public domain dedication,",
        "https://creativecommons.org/publicdomain/zero/1.0/): no attribution required, credited anyway.",
        "Freesound sounds were taken as the public HQ preview (no login needed); the licence was re-checked on",
        "each sound's page at download (`art/tools/freesound.py`, record in `art/source/audio_sources.json`).",
        "",
        "### Kenney.nl (CC0)",
        "",
        "Packs *Interface Sounds*, *UI Audio*, *RPG Audio*, *Music Jingles* by Kenney Vleugels (https://kenney.nl/assets),",
        "licence file `License.txt` in each pack: CC0. Used files:",
        "",
    ]
    for src, users in sorted(USED.items()):
        if src.startswith("kenney:"):
            lines.append(f"- `{src[7:]}` → {', '.join(sorted(users))}")
    lines += ["", "### Freesound (CC0)", "", "| id | title | author | used as |", "|---|---|---|---|"]
    for src, users in sorted(USED.items(), key=lambda kv: kv[0]):
        if not src.startswith("fs:"):
            continue
        sid = src[3:]
        meta = fsreg.get(sid, {})
        title = meta.get("title", "?").replace("|", "/")
        lines.append(f"| [{sid}]({meta.get('page', 'https://freesound.org/s/' + sid + '/')}) | {title} | {meta.get('author', '?')} | {', '.join(sorted(users))} |")
    lines += [
        "",
        "### Synthesised here (original, no third-party material)",
        "",
        "`room_tone`, `slow_pulse` (S10), `instrument_pulse` (S30), `morse` (S29, random letters, no hidden message),",
        "`four_tones` (S49), `drum_loop_muffled` (S27, generic unauthored pattern), `door_chime` (S46),",
        "`doorbell_two_tone` (S05), `metal_tone` (S15), `pa_chime` (S59), `phone_ring` (2020 ringtone) - numpy in",
        "`art/tools/audio_build.py`. `clocks_many` and `valve_clicks` are re-arrangements of the CC0 recordings above.",
        "",
        "### AI-generated sound effects",
        "",
        "None so far (the CC0 sources covered every need; USD 0 of the USD 8 allowance used).",
        "",
    ]
    (ROOT / "art" / "source" / "AUDIO_CREDITS.md").write_text("\n".join(lines), encoding="utf-8")
    print("credits written")


def main() -> None:
    parts = sys.argv[1:] or ["amb", "sfx", "credits"]
    if "amb" in parts:
        build_ambience()
    if "sfx" in parts:
        build_sfx()
    if "credits" in parts:
        if not ("amb" in parts and "sfx" in parts):
            # USED is filled while building; rebuild quietly to know every source
            print("note: credits list only the sources of the parts built in this run")
        build_credits()


if __name__ == "__main__":
    main()
